.PHONY: up down nuke provision bootstrap logs check forge-signoz \
       incident-bad-deploy incident-pool incident-flags incident-leak resolve demo

COMPOSE := docker compose
SIGNOZ_COMPOSE := deploy/signoz/pours/deployment/compose.yaml

# ──────────────────── Lifecycle ────────────────────

# Manifests are generated by Foundry (foundryctl) from deploy/signoz/casting.yaml
# and committed, so this only matters when regenerating (e.g. to bump SigNoz).
forge-signoz:
	@command -v foundryctl >/dev/null || { \
		echo "foundryctl not found — install: curl -fsSL https://signoz.io/foundry.sh | bash"; exit 1; }
	cd deploy/signoz && foundryctl forge -f casting.yaml

up:
	@test -f $(SIGNOZ_COMPOSE) || { echo "Missing $(SIGNOZ_COMPOSE) — run 'make forge-signoz'"; exit 1; }
	@echo "🚀 Starting SigNoz..."
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) up -d
	@echo "⏳ Waiting for SigNoz to be ready..."
	@until curl -sf http://localhost:8080/api/v1/health >/dev/null 2>&1; do printf .; sleep 3; done; echo " ready"
	@echo "🚀 Starting Agent K stack..."
	$(COMPOSE) up -d --build
	@echo "✅ Stack is up! SigNoz UI → http://localhost:8080 | Agent K → http://localhost:9000"

down:
	$(COMPOSE) down
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) down

nuke:
	$(COMPOSE) down -v --remove-orphans
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) down -v --remove-orphans

logs:
	$(COMPOSE) logs -f

logs-%:
	$(COMPOSE) logs -f $*

# ──────────────────── Provisioning ────────────────────

# First-boot SigNoz setup: admin account, service account, API key → .env.
# Idempotent; run once after `make up` on a fresh clone.
bootstrap:
	python3 -m provisioning.bootstrap

provision:
	@echo "📊 Provisioning dashboards & alert rules..."
	$(COMPOSE) exec agent python -m provisioning.provision

# ──────────────────── Chaos / Incidents ────────────────────

incident-bad-deploy:
	@echo "💥 Triggering bad-deploy scenario..."
	$(COMPOSE) run --rm chaos python -m chaos bad-deploy

incident-pool:
	@echo "💥 Triggering pool-exhaustion scenario..."
	$(COMPOSE) run --rm chaos python -m chaos pool-exhaustion

incident-flags:
	@echo "💥 Triggering flag-combo scenario..."
	$(COMPOSE) run --rm chaos python -m chaos flag-combo

incident-leak:
	@echo "💥 Triggering secret-leak scenario..."
	$(COMPOSE) run --rm chaos python -m chaos secret-leak

resolve:
	@echo "✅ Resolving all chaos scenarios..."
	$(COMPOSE) run --rm chaos python -m chaos resolve

# ──────────────────── Demo ────────────────────

demo: up
	@echo "⏳ Waiting for telemetry pipeline to warm up (30s)..."
	@sleep 30
	@echo "📊 Provisioning..."
	@$(MAKE) provision
	@echo "⏳ Letting baseline traffic flow (60s)..."
	@sleep 60
	@echo "💥 Triggering bad-deploy incident..."
	@$(MAKE) incident-bad-deploy
	@echo "🕶️  Agent K is on the case. Watch Slack for the RCA!"

# ──────────────────── Code Quality ────────────────────

check:
	@echo "🔍 Running ruff..."
	ruff check .
	ruff format --check .
	@echo "🧪 Running tests..."
	pytest -x -q
