.PHONY: up down nuke provision provision-fresh bootstrap logs check forge-signoz \
       incident-bad-deploy incident-pool incident-flags incident-leak resolve demo \
       demo-full demo-warm incident-budget verify verify-rubric test-live \
       benchmark benchmark-quick verify-ledger

COMPOSE := docker compose
SIGNOZ_COMPOSE := deploy/signoz/pours/deployment/compose.yaml

# ──────────────────── Lifecycle ────────────────────

# Manifests are generated by Foundry (foundryctl) from deploy/signoz/casting.yaml
# and committed, so this only matters when regenerating (e.g. to bump SigNoz).
forge-signoz:
	@command -v foundryctl >/dev/null || { \
		echo "foundryctl not found — install: curl -fsSL https://signoz.io/foundry.sh | bash"; exit 1; }
	cd deploy/signoz && foundryctl forge -f casting.yaml

up:
	@test -f $(SIGNOZ_COMPOSE) || { echo "Missing $(SIGNOZ_COMPOSE) — run 'make forge-signoz'"; exit 1; }
	@echo "🚀 Starting SigNoz..."
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) up -d
	@echo "⏳ Waiting for SigNoz to be ready..."
	@until curl -sf http://localhost:8080/api/v1/health >/dev/null 2>&1; do printf .; sleep 3; done; echo " ready"
	@echo "🚀 Starting Agent K stack..."
	$(COMPOSE) up -d --build
	@echo "✅ Stack is up! SigNoz UI → http://localhost:8080 | Agent K → http://localhost:9000"

down:
	$(COMPOSE) down
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) down

nuke:
	$(COMPOSE) down -v --remove-orphans
	$(COMPOSE) -f $(SIGNOZ_COMPOSE) down -v --remove-orphans

logs:
	$(COMPOSE) logs -f

logs-%:
	$(COMPOSE) logs -f $*

# ──────────────────── Provisioning ────────────────────

# First-boot SigNoz setup: admin account, service account, API key → .env.
# Idempotent; run once after `make up` on a fresh clone.
bootstrap:
	python3 -m provisioning.bootstrap

provision:
	@echo "📊 Provisioning dashboards & alert rules..."
	$(COMPOSE) exec agent python -m provisioning.provision

provision-fresh:
	@echo "🔄 Fresh-provisioning Agent K resources (delete + recreate)..."
	$(COMPOSE) exec agent python -m provisioning.provision --fresh

test-live:
	python3 scripts/test_live.py

# ──────────────────── Benchmark & Ledger ────────────────────

benchmark:
	@echo "📊 agentk-bench (2 runs/class + healthy control)..."
	python3 scripts/benchmark.py --runs 2

benchmark-quick:
	@echo "📊 agentk-bench (1 run/class, fast)..."
	python3 scripts/benchmark.py --runs 1

verify-ledger:
	python3 scripts/verify_ledger.py

demo-warm: resolve
	@echo "⏳ Baseline traffic (60s)..."
	@sleep 60
	@$(MAKE) incident-bad-deploy
	@echo "⏳ Waiting for investigation via webhook..."
	@python3 scripts/fire_webhook.py bad-deploy
	@echo "👉 Watch reports → http://localhost:9000/reports"

incident-bad-deploy:
	@echo "💥 Triggering bad-deploy scenario..."
	$(COMPOSE) run --rm chaos python -m chaos bad-deploy

incident-pool:
	@echo "💥 Triggering pool-exhaustion scenario..."
	$(COMPOSE) run --rm chaos python -m chaos pool-exhaustion

incident-flags:
	@echo "💥 Triggering flag-combo scenario..."
	$(COMPOSE) run --rm chaos python -m chaos flag-combo

incident-leak:
	@echo "💥 Triggering secret-leak scenario..."
	$(COMPOSE) run --rm chaos python -m chaos secret-leak

resolve:
	@echo "✅ Resolving all chaos scenarios..."
	$(COMPOSE) run --rm chaos python -m chaos resolve

# ──────────────────── Demo ────────────────────

demo: up bootstrap
	@echo "⏳ Waiting for telemetry pipeline to warm up (30s)..."
	@sleep 30
	@echo "📊 Provisioning..."
	@$(MAKE) provision
	@docker compose up -d mcp-server agent
	@echo "⏳ Letting baseline traffic flow (60s)..."
	@sleep 60
	@echo "💥 Triggering bad-deploy incident..."
	@$(MAKE) incident-bad-deploy
	@echo "🕶️  Agent K is on the case. Watch Slack for the RCA!"
	@echo "    SigNoz alert eval ~3 min. Reports → http://localhost:9000/reports"

demo-full: demo
	@echo "⏳ Waiting for alert eval + investigation (up to 4 min)..."
	@sleep 240
	@python3 scripts/verify_checkpoints.py || true
	@echo "👉 Approve rollback via Slack link or: curl 'http://localhost:9000/reports'"

incident-budget:
	@echo "💸 Spiking Agent K LLM budget for self-investigation demo..."
	python3 scripts/incident_budget.py

verify:
	python3 scripts/verify_checkpoints.py

verify-rubric:
	python3 scripts/verify_rubric.py

# ──────────────────── Code Quality ────────────────────

check:
	@echo "🔍 Running ruff..."
	ruff check .
	ruff format --check .
	@echo "🧪 Running tests..."
	pytest -x -q
